BEGIN;

-- =========================================================
-- FLIGALIGA V4 — Migration 002
-- Product catalog foundation
-- =========================================================

-- ---------------------------------------------------------
-- Categories
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT categories_slug_not_blank CHECK (length(trim(slug)) > 0),
    CONSTRAINT unique_category_name UNIQUE (name),
    CONSTRAINT unique_category_slug UNIQUE (slug)
);

-- ---------------------------------------------------------
-- Product catalog fields
-- ---------------------------------------------------------

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS category_id INTEGER;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS fulfillment_method TEXT NOT NULL DEFAULT 'stock';

ALTER TABLE products
    ADD CONSTRAINT products_status_valid
    CHECK (status IN ('draft', 'active', 'archived'));

ALTER TABLE products
    ADD CONSTRAINT products_fulfillment_method_valid
    CHECK (
        fulfillment_method IN (
            'stock',
            'made_to_order',
            'print_on_demand',
            'external'
        )
    );

ALTER TABLE products
    ADD CONSTRAINT products_category_id_fkey
    FOREIGN KEY (category_id)
    REFERENCES categories(id)
    ON DELETE SET NULL;

-- ---------------------------------------------------------
-- Product variants
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS product_variants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    sku TEXT,
    name TEXT,
    price NUMERIC(12,2) NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT product_variants_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT product_variants_price_non_negative
        CHECK (price >= 0),

    CONSTRAINT product_variants_stock_non_negative
        CHECK (stock >= 0),

    CONSTRAINT product_variants_attributes_object
        CHECK (jsonb_typeof(attributes) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_product_variant_sku
    ON product_variants (sku)
    WHERE sku IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_product_variants_product
    ON product_variants (product_id);

CREATE INDEX IF NOT EXISTS idx_product_variants_active
    ON product_variants (is_active);

-- ---------------------------------------------------------
-- Product images
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS product_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT product_images_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT product_images_sort_order_non_negative
        CHECK (sort_order >= 0),

    CONSTRAINT product_images_url_not_blank
        CHECK (length(trim(image_url)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_product_images_product
    ON product_images (product_id, sort_order);

CREATE UNIQUE INDEX IF NOT EXISTS unique_primary_product_image
    ON product_images (product_id)
    WHERE is_primary = TRUE;

-- ---------------------------------------------------------
-- Seed categories from existing product data
-- ---------------------------------------------------------

INSERT INTO categories (name, slug)
SELECT DISTINCT
    TRIM(category),
    lower(regexp_replace(TRIM(category), '[^a-zA-Z0-9]+', '-', 'g'))
FROM products
WHERE category IS NOT NULL
  AND trim(category) <> ''
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------
-- Connect existing products to categories
-- ---------------------------------------------------------

UPDATE products p
SET category_id = c.id
FROM categories c
WHERE p.category_id IS NULL
  AND trim(COALESCE(p.category, '')) <> ''
  AND lower(trim(p.category)) = lower(c.name);

-- ---------------------------------------------------------
-- Create one initial variant for every existing product
-- ---------------------------------------------------------

INSERT INTO product_variants (
    product_id,
    sku,
    name,
    price,
    stock,
    attributes
)
SELECT
    p.id,
    'FLIGALIGA-' || p.id,
    'Default',
    p.price,
    p.stock,
    '{}'::jsonb
FROM products p
WHERE NOT EXISTS (
    SELECT 1
    FROM product_variants v
    WHERE v.product_id = p.id
);

-- ---------------------------------------------------------
-- Copy existing product images into the image system
-- ---------------------------------------------------------

INSERT INTO product_images (
    product_id,
    image_url,
    alt_text,
    sort_order,
    is_primary
)
SELECT
    p.id,
    p.image_url,
    p.name,
    0,
    TRUE
FROM products p
WHERE p.image_url IS NOT NULL
  AND trim(p.image_url) <> ''
  AND NOT EXISTS (
      SELECT 1
      FROM product_images pi
      WHERE pi.product_id = p.id
  );

COMMIT;
