BEGIN;

CREATE TABLE IF NOT EXISTS session (
    sid VARCHAR NOT NULL PRIMARY KEY,
    sess JSON NOT NULL,
    expire TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_session_expire ON session (expire);

CREATE TABLE IF NOT EXISTS withdrawal_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER,
    email TEXT NOT NULL,
    reason TEXT,
    status TEXT NOT NULL DEFAULT 'received',
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT withdrawal_order_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
    CONSTRAINT withdrawal_status_valid CHECK (status IN ('received', 'reviewing', 'completed', 'rejected')),
    CONSTRAINT withdrawal_email_not_blank CHECK (length(trim(email)) > 3)
);

CREATE INDEX IF NOT EXISTS idx_withdrawal_order ON withdrawal_requests (order_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_submitted_at ON withdrawal_requests (submitted_at DESC);

COMMIT;